info.app.name: @project.name@
info.app.artifact: @project.artifactId@
info.app.description: @project.description@
info.app.version: @project.version@
spring.main.banner-mode: "off"
api.path: /cache
server.port: 8080
server.compression.enabled: true
#server.compression.min-response-size: 1
#server.compression.mime-types: application/json,application/xml

# cors
cors:
  enabled: false
  mapping: "/cache/**"
  allowedOrigins: "*"
  allowedMethods: "GET"
  allowCredentials: true

# cache
cache:
  prefix: prebid_
  expiry_sec: 300
  timeout_ms: 300

# logging
logging.level.root: info
logging.config: classpath:log4j2-console.xml

# metrics
metrics:
  graphite:
    enabled: false
    host: localhost
    port: 2003
    prefix: prebid

# endpoint actuators
management.health.defaults.enabled: false
management.endpoints.enabled-by-default: false
management.endpoints.web.base-path: /
management.health.diskspace.enabled: true
management.health.redis.enabled: false
management.endpoints.web.exposure.include: info, health, metrics, env, configprops
management.endpoint.info.enabled: true
management.endpoint.health.enabled: true
management.endpoint.metrics.enabled: true
management.endpoint.env.enabled: true
management.endpoint.configprops.enabled: true
management.endpoint.health.show-details: always
management.endpoint.shutdown.enabled: false
management.endpoint.configprops.keys-to-sanitize: password,secret,key,token,.*credentials.*,vcap_services
management.endpoint.info.cache.time-to-live: 5s
management.endpoint.health.cache.time-to-live: 5s
management.endpoint.metrics.cache.time-to-live: 5s
management.endpoint.env.cache.time-to-live: 5s
management.endpoint.configprops.cache.time-to-live: 5s

# undertow
server.undertow.buffer-size: 16384
server.undertow.direct-buffers: true

---
spring.profiles: manage
management.health.defaults.enabled: true
cors:
  enabled: true
metrics:
  graphite:
    enabled: true

---
spring.profiles: local
cache.expiry_sec: 300
cache:
  min_expiry: 60
  max_expiry: 28800
  secondary_uris:
    - "http://localhost:8080"
  secondary_cache_path : "cache"
metrics.graphite.enabled: false
spring:
  aerospike:
    port: 3000
    host: localhost
    cores: 4
    password:
    first_backoff: 300
    max_backoff: 1000
    max_retry: 3
    namespace: "prebid_cache"
spring.redis.host: localhost
spring.redis.port: 6379
spring.redis.password:
#spring.redis.sentinel.master: mymaster
#spring.redis.sentinel.nodes: localhost:26379

---
# dev
spring.profiles: dev
cache.expiry_sec: 28800
logging.level.root: debug
logging.config: classpath:log4j2-dev.xml

---
# qa
spring.profiles: qa
logging.level.root: info
logging.config: classpath:log4j2-qa.xml

---
# prod
spring.profiles: prod
management.endpoint.metrics.enabled: false
management.endpoint.env.enabled: false
management.endpoint.configprops.enabled: false
logging.level.root: warn
logging.config: classpath:log4j2-prod.xml

